// Generated by scripts/commons.py from assets/credits.json. Do not edit.
window.CREDITS = {
  "assets/img/pesse_canoe.jpg": {
    "title": "File:Boomstamkano van Pesse, Drents Museum, 1955-VIII-2.jpg",
    "author": "Drents Museum",
    "license": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boomstamkano_van_Pesse,_Drents_Museum,_1955-VIII-2.jpg"
  },
  "assets/img/doggerland.jpg": {
    "title": "File:Doggerland.png",
    "author": "James Walker, Vincent Gaffney et al.",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Doggerland.png"
  },
  "assets/img/batavia.jpg": {
    "title": "File:De BATAVIA voor de film onderweg als de NIEUW HOORN (03).jpg",
    "author": "ADZee",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:De_BATAVIA_voor_de_film_onderweg_als_de_NIEUW_HOORN_(03).jpg"
  },
  "assets/img/stokers.jpg": {
    "title": "File:Stettin 1905-0553.jpg",
    "author": "Mozzihh",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Stettin_1905-0553.jpg"
  },
  "assets/img/brunel_chains.jpg": {
    "title": "File:Robert Howlett (Isambard Kingdom Brunel Standing Before the Launching Chains of the Great Eastern), The Metropolitan Museum of Art - restoration1.jpg",
    "author": "Robert Howlett",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Robert_Howlett_(Isambard_Kingdom_Brunel_Standing_Before_the_Launching_Chains_of_the_Great_Eastern),_The_Metropolitan_Museum_of_Art_-_restoration1.jpg"
  },
  "assets/img/torquay_tank.jpg": {
    "title": "File:William Froude and the Admiralty's First Naval Test Tank at Torquay, Devon, C 1872 HU82582.jpg",
    "author": "Royal Navy official photographer",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:William_Froude_and_the_Admiralty%27s_First_Naval_Test_Tank_at_Torquay,_Devon,_C_1872_HU82582.jpg"
  },
  "assets/img/wind_tunnel.jpg": {
    "title": "File:Submarine Model in the NTF - GPN-2000-001290.jpg",
    "author": "NASA/LARC/Paul Bagby",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Submarine_Model_in_the_NTF_-_GPN-2000-001290.jpg"
  },
  "assets/img/centrifuge.jpg": {
    "title": "File:Geotechnical centrifuge at the University of California, Davis..png",
    "author": "Blkutter",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Geotechnical_centrifuge_at_the_University_of_California,_Davis..png"
  },
  "assets/img/mouse.jpg": {
    "title": "File:Домовая мышь (Mus musculus), Москва.jpg",
    "author": "Dion Art",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%D0%94%D0%BE%D0%BC%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BC%D1%8B%D1%88%D1%8C_(Mus_musculus),_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0.jpg"
  },
  "assets/img/flettner.jpg": {
    "title": "File:E-Ship 1 (20037221244).jpg",
    "author": "Alan Jamieson from Aberdeen, Scotland",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:E-Ship_1_(20037221244).jpg"
  },
  "assets/img/kite_ship.jpg": {
    "title": "File:Kite (1).jpg",
    "author": "Yves Parlier",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Kite_(1).jpg"
  },
  "assets/img/ever_given.jpg": {
    "title": "File:Ever Given in Suez Canal viewed from ISS.jpg",
    "author": "NASA JSC ISS image library",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Ever_Given_in_Suez_Canal_viewed_from_ISS.jpg"
  },
  "assets/img/plesiosaur.jpg": {
    "title": "File:Plesiosaur Skeleton with Mary Anning Story (36099767460).jpg",
    "author": "Gary Todd from Xinzheng, China",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Plesiosaur_Skeleton_with_Mary_Anning_Story_(36099767460).jpg"
  },
  "assets/img/froude.jpg": {
    "title": "William Froude",
    "author": "Unknown photographer",
    "license": "Public domain",
    "source": ""
  },
  "assets/img/ventofoil.webp": {
    "title": "VentoFoil 5-series",
    "author": "eConowind",
    "license": "used with permission",
    "source": "https://econowind.nl/ventofoil-family/5-series-ventofoil/",
    "link": "econowind.nl"
  },
  "assets/img/rough_wall_collapsed_surfaces.png": {
    "title": "Machine-discovered rough-wall scaling",
    "author": "Manuel Cabral, TU Delft",
    "license": "used with permission",
    "source": "https://manuel-cabral.github.io/mojito-presentation/"
  },
  "assets/img/elephant_asian.jpg": {
    "title": "File:Asian elephant walking in Tad Lo river at golden hour, Bolaven Plateau, Laos.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Asian_elephant_walking_in_Tad_Lo_river_at_golden_hour,_Bolaven_Plateau,_Laos.jpg"
  },
  "assets/img/clermont.jpg": {
    "title": "File:Clermont (steamboat).JPG",
    "author": "Samuel Ward Stanton",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Clermont_(steamboat).JPG"
  }
};
