// Media layers and missing-asset placeholders.
//
//   <div class="media" data-file="assets/img/x.jpg" data-alt="what it shows"
//        data-credit="Photo: …" data-pos="50% 30%"></div>
//
// Images and videos (.mp4/.webm/.mov, silent, looping) are created here, before
// Reveal initialises, so Reveal's own autoplay handling picks the videos up.
// If the file doesn't exist yet the layer shows a placeholder naming it.

(function () {
  const VIDEO = /\.(mp4|webm|mov)$/i;

  // Attribution from js/credits.js (generated by scripts/commons.py)
  const CREDITS = window.CREDITS || {};
  function creditLine(file) {
    const c = CREDITS[file];
    return c ? `${c.author} · ${c.license}` : '';
  }

  function placeholder(el, file, alt) {
    el.querySelectorAll('img, video').forEach(n => n.remove());
    const ph = document.createElement('div');
    ph.className = 'ph';
    ph.innerHTML =
      `<div class="ph-kind">${VIDEO.test(file) ? 'video' : 'image'} needed</div>` +
      `<div class="ph-alt"></div><div class="ph-file"></div>`;
    ph.querySelector('.ph-alt').textContent = alt;
    ph.querySelector('.ph-file').textContent = file;
    el.prepend(ph);
  }

  function build(el) {
    const file = el.dataset.file, alt = el.dataset.alt || '';
    const isVideo = VIDEO.test(file);
    const node = document.createElement(isVideo ? 'video' : 'img');
    if (isVideo) {
      node.muted = true; node.loop = true; node.playsInline = true;
      node.setAttribute('muted', ''); node.setAttribute('data-autoplay', '');
      node.preload = 'metadata';   // upgraded to 'auto' just before its slide (see below)
    } else {
      node.alt = alt;
      node.decoding = 'async';
    }
    if (el.dataset.pos) node.style.objectPosition = el.dataset.pos;
    // data-view="inset(top right bottom left)" (percentages): show only part of the
    // image/video. The element is given the cropped aspect ratio and the frame
    // is slid inside it with object-fit: cover, which works in every browser.
    if (el.dataset.view) {
      const v = (el.dataset.view.match(/[\d.]+/g) || []).map(Number);
      const [t, r = t, b = t, l = r] = v.map(x => x / 100);
      const crop = () => {
        const w = node.naturalWidth || node.videoWidth, h = node.naturalHeight || node.videoHeight;
        if (!w || !h) return;
        node.style.aspectRatio = `${w * (1 - l - r)} / ${h * (1 - t - b)}`;
        node.style.objectFit = 'cover';
        node.style.objectPosition = `${l + r ? 100 * l / (l + r) : 50}% ${t + b ? 100 * t / (t + b) : 50}%`;
        // auto sizes + max limits: CSS carries each limit through the aspect ratio,
        // so the cropped box fits inside its layer whichever side is tighter
        if (!el.classList.contains('card')) Object.assign(node.style, { width: 'auto', height: 'auto', maxWidth: '100%', maxHeight: '100%' });
        else node.style.width = 'auto';
      };
      el.classList.add('viewbox');
      node.addEventListener(isVideo ? 'loadedmetadata' : 'load', crop);
    }
    // data-start / data-end (seconds): play and loop only that window of a video
    if (isVideo && (el.dataset.start || el.dataset.end)) {
      const t0 = +el.dataset.start || 0, t1 = +el.dataset.end || Infinity;
      node.loop = false;
      // Only seek when the server allows it (HTTP Range; see scripts/serve.py),
      // otherwise a failed seek snaps back to 0 and we would retry forever.
      const canSeek = () => { const s = node.seekable; return s.length && s.end(s.length - 1) >= t0; };
      const toStart = () => { if (canSeek() && Math.abs(node.currentTime - t0) > 0.25) node.currentTime = t0; };
      node.addEventListener('loadedmetadata', toStart);
      node.addEventListener('play', () => { if (node.currentTime < t0 - 0.25) toStart(); });
      node.addEventListener('timeupdate', () => {
        if (node.currentTime >= t1 || (node.currentTime < t0 - 0.25 && !node.seeking)) toStart();
      });
      node.addEventListener('ended', () => { toStart(); node.play().catch(() => {}); });
    }
    node.addEventListener('error', () => placeholder(el, file, alt), { once: true });
    node.src = file;
    el.prepend(node);

    const credit = el.dataset.credit || creditLine(file);
    if (credit) {
      const c = document.createElement('div');
      c.className = 'credit';
      c.textContent = credit;
      const link = (CREDITS[file] || {}).link;   // a website to show on the slide itself
      if (link) {
        const a = document.createElement('a');
        a.href = CREDITS[file].source || `https://${link}`;
        a.textContent = link;
        c.append(' · ', a);
      }
      el.append(c);
    }
  }

  document.querySelectorAll('.media[data-file]').forEach(build);

  // QR codes: <div class="qr" data-qr="URL">, drawn as SVG by vendor/qrcode (MIT)
  document.querySelectorAll('.qr[data-qr]').forEach(div => {
    if (!window.qrcode) return;
    const q = qrcode(0, 'M');
    q.addData(div.dataset.qr);
    q.make();
    div.innerHTML = q.createSvgTag({ cellSize: 8, margin: 2, scalable: true });
  });

  // Credits slide: every credited file that the deck actually uses, in slide order
  const list = document.querySelector('.credits-list');
  if (list) {
    const used = [...new Set([...document.querySelectorAll('.media[data-file]')].map(e => e.dataset.file))];
    used.filter(f => CREDITS[f]).forEach(f => {
      const c = CREDITS[f], li = document.createElement('li');
      const src = c.source ? `<a href="${c.source}">${c.title.replace(/^File:/, '')}</a>` : c.title;
      li.innerHTML = `${src} — ${c.author} · ${c.license}`;
      list.append(li);
    });
  }

  // Only buffer videos on the current and the next slide, so the online deck
  // doesn't pull every clip at once.
  function warm() {
    const slides = Reveal.getSlides(), i = slides.indexOf(Reveal.getCurrentSlide());
    [slides[i], slides[i + 1]].forEach(sl => sl && sl.querySelectorAll('video').forEach(v => {
      v.preload = 'auto';   // a hint only: never reload a clip that may be playing
    }));
  }
  Reveal.on('ready', warm);
  Reveal.on('slidechanged', warm);

  // A video that arrives as a fragment should start from the top when shown.
  Reveal.on('fragmentshown', e => {
    e.fragments.forEach(f => f.querySelectorAll('video').forEach(v => {
      v.currentTime = +(v.parentNode.dataset.start || 0); v.play().catch(() => {});
    }));
  });

  // Light theme: ?light in the URL, or "L" to toggle while presenting.
  // (an attribute, not a class: reveal.js resets <html>'s class list on start)
  const root = document.documentElement;
  if (/[?&]light(=|&|$)/.test(location.search)) root.dataset.theme = 'light';
  Reveal.on('ready', () => Reveal.addKeyBinding(
    { keyCode: 76, key: 'L', description: 'Toggle light theme' },
    () => { root.dataset.theme = root.dataset.theme === 'light' ? 'dark' : 'light'; }));

  // "H" hides placeholders, for rehearsing with a partially filled deck.
  Reveal.on('ready', () => Reveal.addKeyBinding(
    { keyCode: 72, key: 'H', description: 'Toggle placeholders' },
    () => document.body.classList.toggle('hide-placeholders')));
})();
