"""Find and fetch Wikimedia Commons images, keeping their attribution.

    python scripts/commons.py search "Pesse canoe"          # list candidate files
    python scripts/commons.py fetch pesse_canoe.jpg "File:Kano van Pesse.jpg"
    python scripts/commons.py regen      # after hand-editing assets/credits.json

`fetch` saves a ≤2400 px wide rendition to assets/img/<name> and records the
author, license and source page in assets/credits.json. js/credits.js is
regenerated from that file; deck.js shows each credit on its slide and the
closing credits slide lists them all.
"""
import html
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = "https://commons.wikimedia.org/w/api.php"
UA = "StillDesigningShips-slides/0.1 (public lecture deck; python urllib)"
CREDITS = ROOT / "assets" / "credits.json"
sys.stdout.reconfigure(encoding="utf-8")


def get(url, tries=5):
    """GET with a polite pause, backing off when Wikimedia rate-limits (HTTP 429)."""
    for k in range(tries):
        time.sleep(1.0)
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code != 429 or k == tries - 1:
                raise
            time.sleep(int(e.headers.get("Retry-After", 0) or 0) or 5 * 2 ** k)


def api(**params):
    params.update(format="json", formatversion=2)
    return json.loads(get(API + "?" + urllib.parse.urlencode(params)))


def plain(s):
    return html.unescape(re.sub(r"<[^>]+>", "", s or "")).strip()


def info(query_params):
    data = api(action="query", prop="imageinfo", iiprop="url|size|extmetadata",
               iiurlwidth=2400, **query_params)
    return data.get("query", {}).get("pages", [])


def search(term, n=8):
    for p in info(dict(generator="search", gsrsearch=term, gsrnamespace=6, gsrlimit=n)):
        ii = p["imageinfo"][0]
        md = ii.get("extmetadata", {})
        print(f"{p['title']}\n    {ii['width']}×{ii['height']}  "
              f"{plain(md.get('LicenseShortName', {}).get('value'))}  "
              f"{plain(md.get('Artist', {}).get('value'))[:60]}")


def fetch(name, title):
    p = info(dict(titles=title))[0]
    ii = p["imageinfo"][0]
    md = ii.get("extmetadata", {})
    url = ii.get("thumburl") or ii["url"]
    out = ROOT / "assets" / "img" / name
    out.write_bytes(get(url))
    credits = json.loads(CREDITS.read_text(encoding="utf8")) if CREDITS.exists() else {}
    credits[f"assets/img/{name}"] = {
        "title": p["title"],
        "author": plain(md.get("Artist", {}).get("value")) or "unknown",
        "license": plain(md.get("LicenseShortName", {}).get("value")) or "see source",
        "source": ii["descriptionurl"],
    }
    save(credits)
    c = credits[f"assets/img/{name}"]
    print(f"{name}: {out.stat().st_size // 1024} kB  —  {c['author']}, {c['license']}")


def save(credits):
    """Write assets/credits.json and regenerate js/credits.js from it."""
    CREDITS.write_text(json.dumps(credits, indent=2, ensure_ascii=False), encoding="utf8")
    (ROOT / "js" / "credits.js").write_text(
        "// Generated by scripts/commons.py from assets/credits.json. Do not edit.\n"
        f"window.CREDITS = {json.dumps(credits, indent=2, ensure_ascii=False)};\n", encoding="utf8")


def regen():
    """Regenerate js/credits.js after editing assets/credits.json by hand."""
    save(json.loads(CREDITS.read_text(encoding="utf8")))


def peek(outdir, *titles):
    """Save small previews (for choosing) without recording credits."""
    for i, t in enumerate(titles):
        data = api(action="query", prop="imageinfo", iiprop="url", iiurlwidth=700, titles=t)
        url = data["query"]["pages"][0]["imageinfo"][0]["thumburl"]
        Path(outdir, f"peek{i}.jpg").write_bytes(get(url))
        print(f"peek{i}.jpg  {t}")


if __name__ == "__main__":
    cmd, *args = sys.argv[1:]
    {"search": lambda: search(" ".join(args)), "fetch": lambda: fetch(*args),
     "peek": lambda: peek(*args), "regen": regen}[cmd]()
